# Generated by Django 4.1.5 on 2023-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтааа')),
                ('password', models.CharField(max_length=100, verbose_name='Пар0ль')),
            ],
        ),
    ]
